simplecrawler/simplecrawler

lib/crawler.js

If the referer is undefined in the requestOption headers, the plugin terminates with a crash. Tested in windows 7, 64 bit with nodejs 0.12.*. 
Added validation for the same.

Referer undefined validation - in requestOptions

---

.travis.yml
README.markdown

Use node.js 0.12, 0.12 and io.js.
It seems node-simplecraweler has issues with node.js > 0.10  https://github.com/ChrisWren/grunt-link-checker/issues/12

Update Travis config.

---

lib/crawler.js

Test case: crawling of http://www.cetelem.fr/, all default settings
In some case _openRequests gets below zero value, and crawl() complete check never returns true.
After debug i think, that problem here fetchQueueItem() in clientRequest.on("error"). It decrease _openRequests, but have no check that queueItem alredy fetched. No such check also above - in  clientRequest.setTimeout(). 
I dont think, that it's a low level reason, but after adding such checks - problem for me was solved.
Also without this checks clientRequest.setTimeout() sometimes called even after crawler complete its work. 
What do you think about it?

Infinite crawler.crawl() processor

---

README.markdown
lib/crawler.js

Adds a `crawler.ignoreInvalidSSL` options which sets the following options on the https request:
- `client.rejectUnauthorized = false;`
- `client.strictSSL = false;`
Allows, in conjunction with the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable, the use of self-signed SSL certificates. I needed this to run against a https://localhost site which had a self-signed cert.

Add option to allow support for self-signed SSL certificates

---

lib/crawler.js
test/discovery.js

I stumbled across this in one of my projects, took me a while to figure out the server used different codes to encode HTML entities.
Added some tests to prevent regressions in the future.

Added alternative versions of ampersand html encodings

---

lib/crawler.js
test/discovery.js

I discovered this problem while scraping a truly horrible site that was full or URLs of the form `"scripts/run.dll?12341:Project+(Year)"`.  This PR makes a two changes to address these types of URLs:
1. Change the `discoverRegex` list so that trailing quotes or parentheses are kept
2. Change the `cleanURL` function to correctly identify and extract trailing quotes or parentheses.
In the process, I noticed that `discoverRegex` might match the same URL multiple times.  I don't think this is necessarily an issue since duplicate queued items should be passed over, and parsing from the text is a bit of guesswork anyway.  However, I added a comment just to note it in case the issue ever comes up.

Correctly discover URLs that legitimately end with a quote or parenthesis

---

lib/crawler.js

I was having issues where the crawler would stall out when I hit 404's or anything that wasn't a 200. By "stall out" I mean that the process.nextTick callback would not be called for a lengthy period of time with nothing else appearing to run. Adding socket.end() fixed it for some reason. Anyone know why? I couldn't find any documentation in node that explained what was going on.

Stall out on 404's fix

---

README.markdown
example/robots-txt-example.js

By popular demand (#153) , I added an example to show how to integrate simplecrawler with robots-parser, a module that can parse robots.txt files and query URL's against the rules in them.

Added robots.txt parser example

---

lib/crawler.js

In some scenarios, developers might want to provice custom logic for extracting links, but still make use of simplecrawler's internal logic for cleaning and fixing up those links (eg. if you have a DOM parser library and only want to extract links from the href attributes of links). With this change you can call `crawler.cleanExpandResources` to do that!
Also now trimming all discovered resources, since URL's can't actually contain spaces and browsers etc. will ignore any spaces in href attributes.

Expose cleanExpandResources method and trim discovered resources

---

lib/crawler.js
test/reliability.js

Fixes #144. Big problem, small solution. The indefinite hangup of the crawler was due to the fact that I had flipped downloadUnsupported to false (and this problem was triggered in that case).

Decrement _openRequests when mimetype isn't supported

---

test/lib/testserver.js

I ran into a problem when running the test suite, where I was
already running a totally separate server on port 3000, which
caused the tests to bork out completely, without any clue as to
what the cause could be.
Even if it isn't meant to be feature rich, I thought it would be a
good idea to fail loudly if we can't start the testing http server
properly.

Throw error when testing if port 3000 is already in use

---

lib/crawler.js
lib/quickcrawl.js
package.json

URIjs authors renamed the package in the npm registry to urijs (all lowercase), and npm warns about this when installing URIjs. So I changed the name of the package in package.json

Fix URIjs package name

---

lib/crawler.js

Fixes #136. It was possible for timeout events to be emitted after a page had already emitted a 404 event. The reason for this is likely the fact that when 404's are handled, the HTTP response socket is closed, but the request socket isn't. I'm not too familiar with the node http api, but I'm guessing this is why the timeout event for that request can still be emitted.
Just like @fantapop thought, this was likely introduced in 40a71c1c5abffc2729316f4a90a0cb70b056612f, and this change makes simplecrawler behave the way it did before that commit.
Perhaps what's really needed here is for the request socket to be closed together with the response socket (once again, I haven't worked much with the node `http` module directly), but this fixes the problem until further notice anyway.

Prevent timeout events from being emitted when item is already fetched

---

lib/crawler.js
test/discovery.js

They may or may not contain function calls, and since it's a browser protocol, we can safely assume that all content in the href is javascript, so always make sure to replace all of it, only optionally retaining the arguments to any function call.
My issue was that some `"javascript:;"` href's returned `";"`, which is obviously wrong.
I'm almost wondering if it wouldn't be a better idea just to skip trying to retain parts of a `javascript:` href and instead just drop it altogether. It seems unlikely that the argument to any function in there would be a URL?

Better cleaning of "javascript:" href's

---

example/socks-example.js
lib/crawler.js

Also adds a quick SOCKS proxy example (requires the `socksv5` package)
I wasn't sure what the best way to test this was, so I'm open to suggestions. If creating a dummy agent that does nothing is non-trivial (node noob here), that might be an option.

Customizable agent for http / https.

---

lib/quickcrawl.js

Currently when using an HTTPs URL without explicitly specifying the port, the default port is incorrectly determined to be `80` when it should be `443`.

fix: determine port correctly for HTTPs resources

---

lib/cookies.js

Cookies instantiated without a domain get their domain property set
to "*" by default, which seems to imply that they should match any
domain, but matchDomain() did not treat them as such.
* Change matchDomain() to return true for cookies with domain of "*"

Always match cookies with a wild card domain

---

lib/crawler.js

When simplecrawler encounters a lot of URL's that are rejected because of their `Content-Type`, it starts generating DNS errors after a while (`getaddrinfo EMFILE`). It seems this error can arise when a node.js application uses too many sockets ([bug report](https://github.com/nodejs/node-v0.x-archive/issues/7729)). I suspect that simplecrawler is triggering this error by just calling the `end` method on the http response socket, as this might leave the socket open until all data has been received. The problem of sockets not closing in a timely fashion is likely magnified when dealing with resources that might be rejected because of their `Content-Type` - images etc - since they usually are larger than text resources.
Calling the `destroy` method instead of `end` on the sockets when the …

Make sure response sockets are always destroyed

---

lib/crawler.js

This is an attempt at addressing #192. I've also experienced the problem where certain requests are just "left hanging", they're never closed and cause the process to keep running indefinitely unless timed out.
My solution here was to always close HTTP responses on their "end" event.
I don't see any obvious holes in the old logic, my best guess is that the `complete` property for some reason isn't always set on the response when it is in fact complete. I don't see why that would be, but on the other hand I couldn't find any documentation for that property, so there might be some unpredictable behavior there.
The diff is noisier than my actual changes because of an indentation change, but the basic changes are:
1. call `processReceivedData` directly on the request's "end" event
2. always …

New behavior for closing requests

---

README.md
lib/crawler.js
test/lib/routes.js
test/lib/testserver.js
test/testcrawl.js

In rare cases, web servers will send out malformed Set-Cookie
headers that could cause simplecrawler's cookie mechanism to throw
an error. Previously, such an error would kill the entire crawler,
but with this change, the crawler simply emits a "cookieerror"
event and continues. Fixes #184.

Catch errors from adding cookies and emit event

---

README.md
lib/crawler.js
test/discovery.js

We only discover those resources, we don't treat them as an actual
redirect (eg. emit a "fetchredirect" event). Fixes #190

Find resources in <meta> redirects

---

README.md
lib/crawler.js
test/lib/routes.js
test/testcrawl.js

If crawler.allowInitialDomainChange is set to true, and the initial url redirects to a different domain (e.g. a .com redirects to a canonical .net domain), crawler.host is updated to the new domain, to allow crawling to continue on that domain.
The is a re-post of #74.

Add config option to follow initial redirects to a different domain.

---

lib/crawler.js
test/lib/routes.js
test/testcrawl.js

If allowInitialDomainChange is true crawls with maxDepth=1 will fail if depth is not reset.

Redirects should not change the depth on the initial request

---

README.md
lib/crawler.js
test/lib/routes.js
test/resourcevalidity.js

By default, responses that are gzipped or deflated are now
decompressed before they're emitted in the fetchcomplete event.
Previously they have only been decompressed before resource
discovery (and they are still always), but now the
`crawler.decompressResponses` setting (true by default) determines
whether the fetchcomplete response should be decompressed as well.
In theory this could boost performance, since we're doing the same
amount of computation as previously, but with less network
traffic.
Fixes #260

Decompress compressed responses before emitting fetchcomplete

---

lib/crawler.js

For a better understanding whats happening and an increased performance, [Array.prototype.some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) is used instead of [Array.prototype.reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) for lookups.

Use 'Array.protoype.some' instead of 'Array.prototype.reduce' for contains

---

README.md
lib/crawler.js

In addition to #272 (which was btw. just meant to assist developers to debug the current system) I think its useful to provide an option to configure the `whitelistedMimeTypes` for checking which data should be kept after fetching them. Currently these are [hardcoded in the library](https://github.com/cgiffard/node-simplecrawler/blob/master/lib/crawler.js#L614) and can't be modified (e.g. for checking the `text/html` content-type). The modification is focusing on backwards compatibility to existing code and therefore completely optional for cases its needed.
The issue #249 @fredrikekelund mentioned last time will probably cover similar scenarios but won't allow a seamless integration without changing parts of the internals.

Add configuration option for 'whitelistedMimeTypes'

---

lib/crawler.js
test/lib/testserver.js
test/reliability.js

---
Fixes #206.
* Added an additional boolean parameter on the call to stop(), which, if called, will forcibly terminate all in-flight requests.
* Requests are stored in the crawler on crawler._openRequests.
* When a request is complete, it is removed from the request array. This logic is repetitious and could stand to do with some consolidation.
* Calling crawler.stop(true) will loop over this request array and calls request.abort() on each.
* The 'fetchstart' event was moved so it would fire after the request initialisation process. Whether this is a good idea or not is up for debate.
* Tests were added.
This code could really break crawler operation, and to be honest, I'm not feeling that confident about it. Going over it with a fine-toothed come would be very wise.

Crawler: Enabled stop to forcibly terminate in-flight requests

---

README.md
lib/crawler.js

Removes `initialProtocol`, `initialPort` and `initialPath` properties.
They were in fact only being used to construct an initialURL, which is now passed to the constructor in its entirety. It would make more sense to simply remove these properties than to keep them around.

Deprecate initialProtocol, initialPath and initialPort

---

lib/crawler.js
test/resourcevalidity.js

The depth property used to be 2 when a referer wasn't supplied to crawler.processURL. It now is 1.
See #302 
Fixes #302

Fixed depth value of manually queued URL's without referer

---

lib/crawler.js
lib/queue.js
test/queue.js

The final puzzle piece that enables asynchronous queue
implementations! It adds an `update` method to the queue that
takes a URL, an object that describes the updates to be made to
the queue item, and a callback.
I've also made sure that all the places where the crawler mutates
queueItems that are *in the queue* now use this method.
And of course, I've added some tests.
See #257

Only update queue items asynchronously

---

README.md
lib/crawler.js
test/discovery.js
test/lib/routes.js
test/testcrawl.js

If the default Crawler#discoverResources method finds a <meta name="robots" value="nofollow"> tag, it will return an empty array.
See #278

Crawler#respectRobotsTxt now also looks for nofollow robots meta tags

---

lib/queue.js

Fixes #339
This patch try to fix `queue._oldestUnfetchedIndex` calculate error
when `queue.deforst(...)` call. This bug causes queue._oldestUnfetchedIndex
always point to the newest element but not oldest one and skip all
previous queued elements.

Queue.defrost: use Math.min to replace Math.max

---

README.md
lib/crawler.js
package.json
test/conditions.js

It allows async fetch conditions, while maintaining compatibility with previous, synchronous API.
Fixes #345 
@cgiffard comments are welcome! I've added the async dependency to make it easy to asynchronously iterate over the fetch conditions array. Perhaps we could make more use of this module in the future as well. I've also added three new events: `invaliddomain`, `fetchprevented` and `fetchconditionerror`. I went down the verbose route and tried to add more rather than fewer events, but it's probably open for discussion whether or not we need all three of them.

Allow async fetch conditions

---

lib/crawler.js

Deletes requestOptions.port when default blank / no port returned, same as it does when port 80 or 443 specified. 
Currently the getRequestOptions() method in crawler.js deletes the port setting when it's set to a default 80 or 443, but I noticed when connecting in a different https agent that the default port is often blank which should also be deleted here I believe. 
This then fixes also an issue an issue I experienced when using `proxy-agent` as the httpAgent & httpsAgent where for HTTPS requests the port would end up as 80 when passed over as blank. 
Hope this makes sense, thanks.

Fix deleting requestOptions.port when blank/no port set

---

lib/cache.js

The cache backends parameter did not work. It was originally asking for an object, but treating the object like a function. I've changed it to a function that returns an object.

Change cache backend parameter to a function

---

README.md
lib/crawler.js
test/queue.js
test/resourcevalidity.js

I added an option to have crawler sort the query parameters before queuing URL's.
The URLs `http://www.example.com/test.jsp?a=1&b=2` and `http://www.example.com/test.jsp?a=2&b=1` in most cases will return the same content and we want to consider them the same URL. We can canonicalize this URL by sorting the parameters. urijs does this in the [equals()](http://medialize.github.io/URI.js/docs.html#equals) method, but normalize() does not sort the parameters.

Add option to sort Query parameters

---

.eslintrc
.travis.yml
README.md
appveyor.yml
lib/crawler.js

Fixes #364
This refactors the cleanExpandResources method in crawler.js to use a single for loop instead of Array.{filter,map,reduce}. The speedup observed was 20x for a sitemap with 20k urls.
To allow usage of const, let and sets Eslint was bumped to ES6 and Node.js < v4 was dropped from the travis/appveyor configuration.
After creating and analyzing several CPU profiles in Webstorm I decided to get rid of Javascripts native array methods filter, map and reduce, because they are very slow for large arrays. Additionally using a set instead of an array for the result of the reduce part makes a lot more sense because we want to keep unique URLs only.

Performance optimization for very large sitemaps.

---

appveyor.yml

Looks like 30e38b9cad1a86440486d3423446d49b7c7fee70 broke Node.js 8.X tests on AppVeyor.
Fix from https://github.com/appveyor/website/blob/master/appveyor.yml .

Fix AppVeyor configuration.

---

package.json

Fixes #385
With these changes simplecrawler will not queue links such as http://server:port or http:// anymore.
See medialize/URI.js#344 and medialize/URI.js#345

Use latest URI.js, which has improved validation logic.

---

lib/crawler.js
test/discovery.js
test/lib/routes.js

A wrong attribute was used for the meta robots tag:
wrong: ```<meta name='robots' value='nofollow'>```
good: ```<meta name='robots' content='nofollow'>```

Fix wrong meta robots tag attribute

---

lib/cookies.js
lib/crawler.js
test/cookies.js
test/testcrawl.js

`crawler.cookies.getAsHeader()` returns an array of strings with only the name/value pairs. The extra attributes of the cookie are not included. 
When added to `requestOptions.header.cookie` the array of cookies is combined into a single string to avoid bugs in Node versions less than 8.
Resolves issue #397 
Outbound cookies should only include name and value in the header.
In Node.js versions < 8 if `header.cookie` is set to an array, the values a concatenated with commas which is wrong [according to the specs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie). This was [fixed in Node 8](https://github.com/nodejs/node/pull/11259), but for compatibility if we join the cookie values and set `header.cookie` to a string it will always be right.

Send proper outbound cookie header

---

.editorconfig
.gitignore
test/conditions.js
test/depth.js
test/lib/testserver.js
test/queue.js
test/reliability.js
test/resourcevalidity.js
test/testcrawl.js

Currently the tests can't be run independently because they rely on the local server which started in one of the files. That is uncomfortable when working with a particular file. This commit adds the server to every file where necessary.
Also, fixed typo in `.editorconfig` and added WebStorm IDE's project folder to `.gitignore`.

Make tests to run independently

---

lib/crawler.js
test/reliability.js

fix: get rid of multiple `fetchQueueItem` execution for the same items

---

lib/crawler.js
test/lib/routes.js

The constructor `new Buffer` was [deprecated](https://nodejs.org/docs/latest-v10.x/api/buffer.html) since Node.js 6.0.0. The new APIs `Buffer.from` and `Buffer.alloc` [should be used](https://nodejs.org/docs/latest-v10.x/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe) instead.

Rewrite deprecated use of `Buffer`

---

README.md
jsdoc2md/link.hbs

I've noticed that `npm run docs` changes some links in the README as in [this PR](https://github.com/simplecrawler/simplecrawler/pull/457). Looks like the jsdoc2md ignores the `caption` attribute of the link for some reason. I'm not sure if it's an issue or not but was able to fix that with the own link partial.

fix jsdoc2md generated links

---

README.md
lib/crawler.js

Fixes the docs of events `crawlstart` and `discoverycomplete`
~~NOTE: This PR is based on top of #457.  I separated the changes so you can merge that PR first and then review the actual changes in this PR separately.~~
Doc fixes

Fix docs of events `crawlstart` and `discoverycomplete`

---

lib/crawler.js

This pull request is fixing an unimplemented special char case in URLs.

Add a replacement in cleanURL

---

lib/crawler.js
test/lib/routes.js
test/lib/testserver.js
test/notmodified.js

This PR adds If-None-Match or If-Modified-Since header to fetch request
when fetching url is in cache and ETag or Last-Modified value is cached.
This PR also updates queue
on received 304 not-modified response from server.
Otherwise, crawler does not emit "complete" event.
This PR resolves #375.

cache: send headers If-None-Match and If-Modified-Since
